export const defaultSearchOptions = {
  query: "",
  entityTypeIds: [],
  //nextEntityType: [],
  nextEntityType: "",
  nextEntityTypes: [],
  start: 1,
  pageNumber: 1,
  pageLength: 20,
  pageSize: 20,
  selectedFacets: {},
  maxRowsPerPage: 100,
  selectedQuery: "select a query",
  manageQueryModal: false,
  selectedTableProperties: [],
  view: null,
  sortOrder: [],
  baseEntities: [],
  conceptFilterTypeIds: [],
  mergeUnmerge: false,
  preselectedFacets: [],
  setSearchFromUserPref: () => {},
  setSavedNode: () => {},
  setQuery: () => {},
  relatedEntityTypeId: [],
  relatedEntityTypeIds: [],
  sidebarQuery: "Select a saved query",
  tileId: "explore",
  database: "final",
  datasource: "entities",
};

export const searchContextInterfaceByDefault = {
  searchOptions: defaultSearchOptions,
  greyedOptions: defaultSearchOptions,
  setRelatedEntityTypeIds: jest.fn(),
  setConceptFilterTypeIds: jest.fn(),
  setAllFilterTypeIds: jest.fn(),
  setEntity: jest.fn(),
  applySaveQuery: jest.fn(),
  savedNode: undefined,
  setSavedNode: jest.fn(),
  setSearchFromUserPref: jest.fn(),
  setQuery: jest.fn(),
  setPage: jest.fn(),
  setPageLength: jest.fn(),
  toggleMergeUnmerge: jest.fn(),
  setSearchFacets: jest.fn(),
  setEntityTypeIds: jest.fn(),
  setNextEntity: jest.fn(),
  setEntityClearQuery: jest.fn(),
  setLatestJobFacet: jest.fn(),
  clearFacet: jest.fn(),
  clearAllFacets: jest.fn(),
  clearAllFacetsLS: jest.fn(),
  clearDateFacet: jest.fn(),
  clearRangeFacet: jest.fn(),
  clearGreyDateFacet: jest.fn(),
  clearGreyRangeFacet: jest.fn(),
  resetSearchOptions: jest.fn(),
  setAllSearchFacets: jest.fn(),
  setAllGreyedOptions: jest.fn(),
  setQueryGreyedOptions: jest.fn(),
  clearGreyFacet: jest.fn(),
  clearConstraint: jest.fn(),
  clearAllGreyFacets: jest.fn(),
  resetGreyedOptions: jest.fn(),
  setSelectedQuery: jest.fn(),
  setSidebarQuery: jest.fn(),
  setSelectedTableProperties: jest.fn(),
  setBaseEntitiesWithProperties: jest.fn(),
  setView: jest.fn(),
  setPageWithEntity: jest.fn(),
  setSortOrder: jest.fn(),
  savedQueries: jest.fn(),
  setSavedQueries: jest.fn(),
  setDatabase: jest.fn(),
  setLatestDatabase: jest.fn(),
  entityDefinitionsArray: jest.fn(),
  setEntityDefinitionsArray: jest.fn(),
  setGraphViewOptions: jest.fn(),
  setDatasource: jest.fn(),
  setSearchOptions: jest.fn(),
  entityInstanceId: "",
  setDatabaseAndDatasource: jest.fn(),
};
