<?xml version="1.0" encoding="UTF-8"?>
<!--This file is autogenerated. Please don't edit.-->
<flow xmlns="http://marklogic.com/data-hub">
  <complexity>simple</complexity>
  <data-format>application/json</data-format>
  <plugins/>
</flow>

