version: 1.0.{build}
branches:
  only:
  - master
image: WMF 5
environment:
  ML_USER:
    secure: nioOZ/YaPcyFoqN9bVZHMllinShpPT+lG1uyi78H23c=
  ML_PASSWORD:
    secure: LaFtKimqM2zAtGUkciP5RA==
  ML_VERSION: 8.0-5.1
install:
- ps: >-
    function HttpPost($cookieContainer, $url, $postData) {
        $uri = New-Object "System.Uri" "$url"
        $webrequest = [System.Net.HTTPWebRequest]::Create($uri)
        $webrequest.CookieContainer = $cookieContainer
        $webrequest.ContentType = "application/x-www-form-urlencoded"
        $webrequest.Method = "POST"

        $encoding = New-Object System.Text.ASCIIEncoding
        $bytes = $encoding.GetBytes($postData)
        $webrequest.ContentLength = $bytes.Length

        $newStream = $webrequest.GetRequestStream()
        $newStream.Write($bytes, 0, $bytes.Length)
        $response = $webrequest.GetResponse().GetResponseStream()
        $sr = New-Object System.IO.StreamReader($response)
        $respTxt = $sr.ReadToEnd()
        $sr.Close()
        $response.Dispose()
        return $respTxt
    }

    function downloadFile($cookieContainer, $url, $targetFile) {
        $cookie = $cookieContainer.GetCookies("https://developer.marklogic.com")[0]
        $cookieTxt = $cookie.NAME + "=" + $cookie.Value
        $wc = New-Object System.Net.WebClient
        $wc.Headers.Add([System.Net.HttpRequestHeader]::Cookie, $cookieTxt)
        $wc.DownloadFile($url, $targetFile)
    }

    $cookieContainer = New-Object System.Net.CookieContainer
    $email = $env:ML_USER
    $password = $env:ML_PASSWORD
    $loginData = "email=$email&password=$password"

    # Login
    $url = "https://developer.marklogic.com/login"
    $response = HttpPost $cookieContainer $url $loginData

    # Get Download url
    $ver = $env:ML_VERSION
    $fname = "MarkLogic-$ver-amd64.msi"
    $url = "https://developer.marklogic.com/get-download-url"
    $postData = "download=/download/binaries/8.0/$fname"
    $response = HttpPost $cookieContainer $url $postData
    $json = $response | ConvertFrom-Json
    $downloadLink = $json.path
    $downloadLink = "https://developer.marklogic.com$downloadLink"

    # Download File
    downloadFile $cookieContainer $downloadLink "$PSScriptRoot\$fname"
    msiexec /i "$PSScriptRoot\$fname" /quiet /qn /norestart /log install.log
    Start-Sleep -s 90
    cat .\install.log
    Start-Service -displayname "MarkLogic"
    HttpPost $cookieContainer "http://localhost:8001/admin/v1/init" ""
    Start-Sleep -s 10
    $postData = "admin-username=admin&admin-password=admin&realm=public"
    HttpPost $cookieContainer "http://localhost:8001/admin/v1/instance-admin" $postData
    Start-Sleep -s 10
build: off
test_script:
- ps: >-
    c:
    cd \projects\marklogic-data-hub
    .\gradlew.bat test