export const flowsModelArray = [{
  "id": "flow-1",
  "name": "Order Flow 01",
  "description": "My Flow01 flow desc",
  "batchSize": 100,
  "threadCount": 4,
  "options": {"key": "value", "key2": "value1", "key3": "value1"},
  "steps": [{
    "id": "step-1-flow-1",
    "name": "Flow 01 Ingest Step",
    "description": "My Step 1 description",
    "type": "ingestion",
    "sourceDatabase": "",
    "targetDatabase": "staging",
    "isValid": true,
    "isRunning": false,
    "config": {"mlcp": "options"},
    "lang": "en",
    "version": "1"
  }, {
    "id": "step-2-flow-1",
    "name": "Flow 01 Mapping Step",
    "description": "My Step 2 description",
    "type": "mapping",
    "sourceDatabase": "",
    "targetDatabase": "staging",
    "isValid": true,
    "isRunning": false,
    "config": {"mlcp": "options"},
    "lang": "en",
    "version": "1"
  }, {
    "id": "step-3-flow-1",
    "name": "Flow 01 Mastering Step",
    "description": "My Step 3 description",
    "type": "mastering",
    "sourceDatabase": "",
    "targetDatabase": "staging",
    "isValid": true,
    "isRunning": false,
    "config": {"mlcp": "options"},
    "lang": "en",
    "version": "1"
  }, {
    "id": "step-4-flow-1",
    "name": "Flow 01 Custom Step",
    "description": "My Step 4 description",
    "type": "custom",
    "sourceDatabase": "",
    "targetDatabase": "staging",
    "isValid": true,
    "isRunning": false,
    "config": {"mlcp": "options"},
    "lang": "en",
    "version": "1"
  }],
  "jobs": ["job-1-flow-1", "job-2-flow-1", "job-3-flow-1", "job-4-flow-1"],
  "latestJob": {
    "id": "job-4-flow-1",
    "flowId": "flow-1",
    "startTime": "2019-01-31 12:10:00",
    "endTime": "2019-01-31 13:10:00",
    "output": [],
    "status": "running",
    "runningPercent": 85,
    "successfulEvents": 500,
    "failedEvents": 0
  },
  "isValid": true,
  "isRunning": false,
  "version": 1
}, {
  "id": "flow-2",
  "name": "Order Flow 2",
  "description": "My Flow2 flow desc",
  "batchSize": 100,
  "threadCount": 4,
  "options": {"key": "value", "key2": "value1", "key3": "value1"},
  "steps": [{
    "id": "step-1-flow-2",
    "name": "Flow 02 Ingest Step",
    "description": "My Step 1 description",
    "type": "ingestion",
    "sourceDatabase": "",
    "targetDatabase": "staging",
    "isValid": true,
    "isRunning": false,
    "config": {"mlcp": "options"},
    "lang": "en",
    "version": "1"
  }, {
    "id": "step-2-flow-2",
    "name": "Flow 02 Mapping Step",
    "description": "My Step 2 description",
    "type": "mapping",
    "sourceDatabase": "",
    "targetDatabase": "staging",
    "isValid": true,
    "isRunning": false,
    "config": {"mapping": "options"},
    "lang": "en",
    "version": "1"
  }, {
    "id": "step-3-flow-2",
    "name": "Flow 02 Mastering Step",
    "description": "My Step 3 description",
    "type": "mastering",
    "sourceDatabase": "",
    "targetDatabase": "staging",
    "isValid": true,
    "isRunning": false,
    "config": {"mastering": "options"},
    "lang": "en",
    "version": "1"
  }, {
    "id": "step-4-flow-2",
    "name": "Flow 02 Custom Step",
    "description": "My Step 4 description",
    "type": "custom",
    "sourceDatabase": "",
    "targetDatabase": "staging",
    "isValid": true,
    "isRunning": false,
    "config": {"custom": "options"},
    "lang": "en",
    "version": "1"
  }],
  "jobs": ["job-1-flow-2", "job-2-flow-2", "job-3-flow-2", "job-4-flow-2"],
  "latestJob": {
    "id": "job-4-flow-2",
    "flowId": "flow-2",
    "startTime": "2019-02-01 12:10:00",
    "endTime": "2019-02-01 16:10:00",
    "output": [],
    "status": "finished",
    "runningPercent": null,
    "successfulEvents": 13429,
    "failedEvents": 63
  },
  "isValid": true,
  "isRunning": false,
  "version": 1
}, {
  "id": "flow-3",
  "name": "Customer Flow",
  "description": "My Customer Flow flow desc",
  "batchSize": 100,
  "threadCount": 4,
  "options": {"key": "value", "key2": "value1", "key3": "value1"},
  "steps": [{
    "id": "step-1-flow-3",
    "name": "Flow 3 Ingest Step",
    "description": "My Step 1 description",
    "type": "ingestion",
    "sourceDatabase": "",
    "targetDatabase": "staging",
    "isValid": true,
    "isRunning": false,
    "config": {"mlcp": "options"},
    "lang": "en",
    "version": "1"
  }, {
    "id": "step-2-flow-3",
    "name": "Flow 3 Mapping Step",
    "description": "My Step 2 description",
    "type": "mapping",
    "sourceDatabase": "",
    "targetDatabase": "staging",
    "isValid": true,
    "isRunning": false,
    "config": {"mapping": "options"},
    "lang": "en",
    "version": "1"
  }, {
    "id": "step-3-flow-3",
    "name": "Flow 3 Mastering Step",
    "description": "My Step 3 description",
    "type": "mastering",
    "sourceDatabase": "",
    "targetDatabase": "staging",
    "isValid": true,
    "isRunning": false,
    "config": {"mastering": "options"},
    "lang": "en",
    "version": "1"
  }, {
    "id": "step-4-flow-3",
    "name": "Flow 3 Custom Step",
    "description": "My Step 4 description",
    "type": "custom",
    "sourceDatabase": "",
    "targetDatabase": "staging",
    "isValid": true,
    "isRunning": false,
    "config": {"custom": "options"},
    "lang": "en",
    "version": "1"
  }],
  "jobs": ["job-1-flow-3"],
  "latestJob": {
    "id": "job-1-flow-3",
    "flowId": "flow-3",
    "startTime": "2019-02-02 12:10:00",
    "endTime": "2019-02-02 16:10:00",
    "output": [],
    "status": "errored",
    "runningPercent": null,
    "successfulEvents": 0,
    "failedEvents": 500
  },
  "isValid": true,
  "isRunning": false,
  "version": 1
}, {
  "id": "flow-3",
  "name": "Product Ingestion",
  "description": "My Product Ingestion Flow flow desc",
  "batchSize": 100,
  "threadCount": 4,
  "options": {"key": "value", "key2": "value1", "key3": "value1"},
  "steps": [{
    "id": "step-1-flow-3",
    "name": "Flow 3 Ingest Step",
    "description": "My Step 1 description",
    "type": "ingestion",
    "sourceDatabase": "",
    "targetDatabase": "staging",
    "isValid": false,
    "isRunning": false,
    "config": {"mlcp": "options"},
    "lang": "en",
    "version": "1"
  }],
  "jobs": [],
  "latestJob": null,
  "isValid": false,
  "isRunning": false,
  "version": 1
}];
