FROM centos:centos7

ENV LANG C.UTF-8
ENV JAVA_VERSION 8u131
ENV BUILD_VERSION b11
ENV SUM d54c1d3a095b4ff2b6607d096fa80163
RUN yum -y install glibc.i686 \
    gdb.x86_64 redhat-lsb.x86_64 vim \
    bzip2 \
    unzip \
    wget \
    xz-utils 2>&1 > /dev/null

# Downloading Java
RUN wget --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/$JAVA_VERSION-$BUILD_VERSION/$SUM/jdk-$JAVA_VERSION-linux-x64.rpm" -O /tmp/jdk-8-linux-x64.rpm
RUN yum -y install /tmp/jdk-8-linux-x64.rpm

RUN alternatives --install /usr/bin/java jar /usr/java/latest/bin/java 200000
RUN alternatives --install /usr/bin/javaws javaws /usr/java/latest/bin/javaws 200000
RUN alternatives --install /usr/bin/javac javac /usr/java/latest/bin/javac 200000

ENV JAVA_HOME /usr/java/latest

# Install MarkLogic
COPY ./MarkLogic.rpm /tmp/MarkLogic.rpm

RUN yum -y install /tmp/MarkLogic.rpm 2>&1 > /dev/null

# Expose MarkLogic Server ports - add additional ones for your REST, etc
# endpoints
EXPOSE 7997-8020

# init
COPY .travis/startml.sh /tmp/startml.sh
RUN chmod 755 /tmp/startml.sh
COPY .travis/setup.sh /tmp/setup.sh
RUN chmod 755 /tmp/setup.sh
RUN /tmp/setup.sh

VOLUME /marklogic-data-hub
ADD ./ /marklogic-data-hub
WORKDIR /marklogic-data-hub

RUN ./gradlew build -x test 2>&1 > /dev/null

# Define default command (which avoids immediate shutdown)
CMD /tmp/startml.sh && ./gradlew test
