xquery version "1.0-ml";

import module namespace hub-test = "http://marklogic.com/data-hub/test" at "/test/data-hub-test-helper.xqy";
import module namespace test = "http://marklogic.com/test" at "/test/test-helper.xqy";

hub-test:load-entities($test:__CALLER_FILE__);


xquery version "1.0-ml";

import module namespace hub-test = "http://marklogic.com/data-hub/test" at "/test/data-hub-test-helper.xqy";
import module namespace test = "http://marklogic.com/test" at "/test/test-helper.xqy";

hub-test:load-non-entities($test:__CALLER_FILE__),

(: Clear out Jobs so we can easily assert against the ones generated by the tests :)
xdmp:invoke-function( function () {
xdmp:collection-delete("Jobs")
},
<options xmlns="xdmp:eval">
<database>{xdmp:database("data-hub-JOBS")}</database>
</options>
)
